// Generated by https://quicktype.io

export interface Resource {
  name: string;
  description: string;
  url: string;
  date: string;
  categoryName:
    | 'Accesibilidad'
    | 'Imagenes'
    | 'Animaciones'
    | 'Background'
    | 'Blog'
    | 'Iconos'
    | 'Cursos'
    | 'Colores'
    | 'Fuentes'
    | 'Git';
}
